language: node_js
sudo: required
dist: trusty
addons:
    chrome: stable
node_js:
- 10
env:
  global:
  - NODE_ENV=production
  - SMOKE_URL=http://smalruby.jp/smalruby3-gui/
  - NPM_TAG=latest
cache:
  directories:
  - node_modules
install:
- npm --production=false install
- npm --production=false update
script:
- npm run test:lint
- npm run test:unit
- npm run clean && $(npm bin)/webpack --colors --bail --silent
- npm run test:integration
deploy:
- provider: script
  on:
    branch:
    - develop
  skip_cleanup: true
  script: npm run deploy -- -x -r https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
